### ISSUE TITLE
Is your pipeline work on WES ?

### ISSUE THREAD

**Issue by lmanchon** [mpiersonsmela/SeqVerify#5]

**Comment by mpiersonsmela** [comment]
The pipeline is designed for WGS data, not WES. However, you could try the alignment and variant calling portions of the pipeline with WES data. We have not tested this but I think these portions of the pipeline are likely to be OK, although I can't guarantee the results will be useful.

The other portions of the pipeline (insertion site detection and CNV analysis) are unlikely to work with WES data.

**Comment by lmanchon** [comment]
Hi,
ok thanks for the answer, so another question: is CNVpytor compute BAF for CNV detected ?

**Comment by mpiersonsmela** [comment]
CNVpytor can use BAF data (see: https://github.com/abyzovlab/CNVpytor?tab=readme-ov-file#importing-and-using-single-nucleotide-polymorphism-data) but we do not use BAF in SeqVerify, because read depth is a better measure of copy number than BAF.

**Comment by lmanchon** [comment]
BAF is linked to sequencing depth, but also to the presence of a SNV and the calculation of VAF for this SNV
(see: https://jp.support.illumina.com/content/dam/illumina-support/help/Illumina_DRAGEN_Bio_IT_Platform_v3_7_1000000141465/Content/SW/Informatics/Dragen/BAlleleFrequencyOutput_fDG.htm)
